### Query all music.
GET http://127.0.0.1:8000/all
Accept: application/json

### Query title.
GET http://127.0.0.1:8000/?title=Migration
Accept: application/json

### Query artist.
GET http://127.0.0.1:8000/?artist=The%20Lumineers
Accept: application/json


### Query year.
GET http://127.0.0.1:8000/?year=2013
Accept: application/json


### Query title and artist.
GET http://127.0.0.1:8000/?title=Lola&artist=The%20Kinks
Accept: application/json


### Query title and year.
GET http://127.0.0.1:8000/?title=Harvest&year=1972
Accept: application/json

### Query artist and year.
GET http://127.0.0.1:8000/?artist=Emmylou%20Harris&year=2000
Accept: application/json

### Query invalid title.
GET http://127.0.0.1:8000/?title=Invalid
Accept: application/json

### Query invalid artist.
GET http://127.0.0.1:8000/?artist=Invalid

### Query invalid year.
GET http://127.0.0.1:8000/?year=1267821